# -*- coding: utf-8 -*-
"""SPL Warung Makan

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11QcrrXCVpMAKh7KhZ1FL0_bOySq8IhCo
"""

import numpy as np

A = np.array([
    [3, 3, 1],
    [1, 3, 2],
    [1, 2, 2]
], dtype=float)


B = np.array([55000, 40000, 30000], dtype=float)


A_inv = np.linalg.inv(A)
X = A_inv @ B

N, A_item, T = X

print("=== HASIL DARI OPERASI MATRIKS (X = A^{-1}B) ===")
print("Harga Nasi  (N) = Rp", int(round(N)))
print("Harga Ayam  (A) = Rp", int(round(A_item)))
print("Harga Teh   (T) = Rp", int(round(T)))


harga_paket_A = N + A_item
harga_paket_B = N + A_item + T
harga_paket_C = A_item + T

print()

print("=== VERIFIKASI HARGA PAKET ===")
print("2 Paket A + 1 Paket B =",
      2 * harga_paket_A + harga_paket_B,
      "(seharusnya 55000)")
print("1 Paket A + 2 Paket C =",
      harga_paket_A + 2 * harga_paket_C,
      "(seharusnya 40000)")
print("1 Paket B + 1 Paket C =",
      harga_paket_B + harga_paket_C,
      "(seharusnya 30000)")